name=Noise Monitor UNE-EN ISO 1996-2
version=3.0.0
author=Roberto Fernandez
maintainer=Roberto Fernandez
sentence=ESP32-C3 I2C noise monitor with L_Aeq, Ld/Le/Ln, Lden. ISO 1996-2, Decreto 213/2012.
paragraph=ADC + A-weighting DSP, MAX4466 support. Slave firmware and calibration example.
category=Sensors
url=https://github.com/roberbike/noise_UNE-EN_ISO_1996-2-2009
architectures=esp32
depends=
