name=Noise Monitor UNE-EN ISO 1996-2
version=3.3.3
author=Roberto Fernandez
maintainer=Roberto Fernandez
sentence=ESP32-C3 and ESP32-S3 I2C environmental noise monitor following UNE-EN ISO 1996-2.
paragraph=ADC/MAX4466 and digital I2S/ICS-43434 nodes with A-weighted levels, L10/L90, Ld/Le/Ln and Lden. Includes slave firmware and calibration examples.
category=Sensors
url=https://github.com/roberbike/noise_UNE-EN_ISO_1996-2-2009
architectures=esp32
depends=
